spring:
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    # url: jdbc:dm://localhost:5236?comOracle=true
    # url: jdbc:dm://localhost:5236?compatibleMode=oracle
    # url: jdbc:dm://localhost:5236?comOracle=true&databaseProductName=Oracle&compatibleMode=oracle
    url: jdbc:dm://localhost:5236
    username: test
    password: test123456
  # flyway在spring boot中默认配置位置为：classpath:db/migration
  # flyway命名规则为：V<VERSION>__<NAME>.sql (with <VERSION> an underscore-separated version, such as ‘1’ or ‘2_1’)
  flyway:
    # 默认不启用，true 为启用
    enabled: true
    baseline-on-migrate: true
    # 禁用 placeholder replacement，否则 sql 脚本中不能写 ${} 这样的字符。
    placeholder-replacement: false
    locations:
      - classpath:db/migration/dm
      # - classpath:db/migration/h2
      # - classpath:db/migration/mysql
      # - classpath:db/migration/oracle